# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Alla Isakova
title: Fairy tales of San Francisco &hearts;
email: karmelalla@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Спасибо за уделенное время. Надеюсь, вам понравилось! =)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: karmelalla
instagram_username: karmelalla
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
excerpt_separator: "<!--separate-->"
disqus:
  shortname: lostdream-ru
domain: "http://karmelalla.com"
mail_subject: "Новый пост на karmelalla.com:"
mail_intro: "Привет! <br><br>На моем сайте вышел новый пост:"
mail_read_more: "читать далее..."
mail_closing: "Пожалуйста, оставляйте свои комментарии или ставьте сердечко под постом. Мне будет очень приятно! <br><br>Алла"

paginate: 10
image_width: 2048
image_small_width: 300
image_quality: 90

timezone: "America/Los_Angeles"

